fix(email data): do not collect data if cluster was not created
If cluster creation failed (for example, I got it in the siren-test), got
error while saving email data:
Error: 'NoneType' object has no attribute 'get_node_benchmarks_results'

If cluster was not created, we do not need to collect benchmarks results and
nemesis stats